# Generated by Django 3.2.18 on 2023-03-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20230306_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['-updated_at'], 'verbose_name': 'ลูกหนี้', 'verbose_name_plural': 'ข้อมูลลูกหนี้'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
