# Generated by Django 4.1.3 on 2023-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_exp_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='EXP',
            field=models.DateField(blank=True),
        ),
    ]
