# Generated by Django 3.2.18 on 2023-03-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitproduct',
            name='description',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
