# Generated by Django 4.1.3 on 2023-02-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_debtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['updated_at'], 'verbose_name': 'ข้อมูลลูกหนี้', 'verbose_name_plural': 'ข้อมูลลูกหนี้'},
        ),
        migrations.AddField(
            model_name='debtor',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='debtor',
            table='debtor',
        ),
    ]
