# Generated by Django 4.1.3 on 2023-03-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_debtor_options_debtor_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255, null=True)),
                ('profitTotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'กำไร',
                'verbose_name_plural': 'ข้อมูลกำไร',
                'db_table': 'ProfitProduct',
                'ordering': ['updated_at'],
            },
        ),
    ]
