# Generated by Django 4.1.3 on 2023-03-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_profitproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitproduct',
            name='nameProduct',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
